dist/cases.json
openapi.yaml
openapi/components/schemas/cases/enums/FiltroTipoProfissionalAgenda.yaml
openapi/paths/cases/agenda/public@api@compromissos-get.yaml

Adição do parametro do tipo enum para filtro na listagem de itens agenda por funcionario
closes issue #19757

feat(Adição novo parametro)

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTONaturezaCompleto.yaml
openapi/components/schemas/cases/enums/GrupoNaturezaDaCausa.yaml
openapi/components/schemas/cases/enums/RamosJudicial.yaml
openapi/paths/cases/natureza/public@api@natureza-get.yaml

docs: adicionando documentação de listar naturezas

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTOParametrosCaso.yaml
openapi/components/schemas/cases/enums/SituacaoDoProcesso.yaml
openapi/paths/cases/casos/public@api@casos@por_pagina-get.yaml

docs: api/casos/por_pagina documentation

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOCasoCompleto.yaml
openapi/components/schemas/cases/DTOCasoFicha.yaml
openapi/components/schemas/cases/DTOCasoSimples.yaml

feat: adicionando propriedade IDsNaturezasDoCaso

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOCasoSimples.yaml

Adicionando propriedade no DTOCasoSimples.yaml
AB#21702

feat(MobileService): Nova propriedade Rito

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOCasoCompleto.yaml
openapi/components/schemas/cases/DTOCasoSimples.yaml
openapi/components/schemas/cases/enums/SituacaoDoProcesso.yaml

feat(OpenAPI): Refatoração e inserção de dados na documentação
AB#21834

feat(OpenAPI): Refatoração e inserção de dados na documentação

---

.redocly.yaml
dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOProcessoPreCadastro.yaml

Inclusão dos idsNatureza no DTOProcessoPreCadastro no cadastro do caso
AB#22086

fix(OpenAPI)

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/ParteParaLO.yaml

Inclusão da propriedade tipoEnvolvimento (cdPartePapel)
AB#22116

fix(OpenAPI): Inclusão da propriedade tipoEnvolvimento

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTOCumprimento.yaml
openapi/components/schemas/cases/FiltroCumprimentos.yaml
openapi/paths/cases/cumprimentos/public@api@Pedidos@cdPedido@cumprimentos-delete.yaml
openapi/paths/cases/cumprimentos/public@api@cumprimentos-get.yaml
openapi/paths/cases/cumprimentos/public@api@cumprimentos-post.yaml
openapi/paths/cases/cumprimentos/public@api@cumprimentos-put.yaml
openapi/paths/cases/cumprimentos/public@api@cumprimentos@ListaComFiltro-post.yaml
openapi/paths/cases/cumprimentos/public@api@cumprimentos@exclui-delete.yaml

feat(Cumprimentos): AB#22214 Implementação de endpoints de cumprimentos

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTOAttorneyFeeInfo.yaml
openapi/components/schemas/cases/DTOCalculationAdjustmentRates.yaml
openapi/components/schemas/cases/DTOCalculationFactors.yaml
openapi/components/schemas/cases/DTOCompensatoryInterestItem.yaml
openapi/components/schemas/cases/DTOCumprimento.yaml
openapi/components/schemas/cases/DTOCurrencyValue.yaml
openapi/components/schemas/cases/DTODefaultInterestItem.yaml
openapi/components/schemas/cases/DTOExchangeRebateInfo.yaml
openapi/components/schemas/cases/DTOExchangeResultItem.yaml
openapi/components/schemas/cases/DTOExchangeResultItemSingleOccurence.yaml
openapi/components/schemas/cases/DTOExchangeResultItemSingleOccurenceIntervalValues.yaml
openapi/components/schemas/cases/DTOExchangeSingleResultAttorneyFee.yaml
openapi/components/schemas/cases/DTOExchangeSingleResultCompensatoryInterest.yaml
openapi/components/schemas/cases/DTOExchangeSingleResultFine.yaml
openapi/components/schemas/cases/DTOExchangeSingleResultInterestInArrears.yaml
openapi/components/schemas/cases/DTOPenaltyInfo.yaml
openapi/components/schemas/cases/DTOResultadoCalculo.yaml
openapi/components/schemas/cases/DTOSingleAttorneyFeeInfo.yaml
openapi/components/schemas/cases/DTOTMPPedido.yaml
openapi/components/schemas/cases/FilterTMPProcessoExpectativaReivindicacao.yaml
openapi/components/schemas/cases/FiltroCumprimentos.yaml
openapi/paths/cases/liabilitiesCalculation/public@api@liabilitiesCalculation@calculaCaso-post.yaml
openapi/paths/cases/pedidos/public@api@pedidostmp-post.yaml

temporal pedidos
e
calcula caso

feat(Cumprimentos): AB#22138 endpoints de cumprimentos

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTOAcaoPush.yaml
openapi/components/schemas/cases/DTOPublicacao.yaml
openapi/components/schemas/cases/enums/FornecedorPush.yaml
openapi/components/schemas/cases/enums/SituacaoPublicacao.yaml
openapi/components/schemas/cases/enums/StatusDaPublicacao.yaml
openapi/components/schemas/cases/enums/TipoDeAcao.yaml
openapi/components/schemas/cases/enums/TipoPesquisaPublicacao.yaml
openapi/paths/cases/push/public@api@publicacao@por_pagina-get.yaml
yarn.lock

[AB#23885](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/23885)

docs: endpoint of paginated publications

---

dist/cases.json
openapi.yaml
openapi/paths/cases/casos/public@api@casos@por_pagina-get.yaml
openapi/paths/cases/push/public@api@publicacao@por_pagina-get.yaml

[AB#23934](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/23934)

fix: ajustando descrição da propriedade pageSize

---

dist/cases.json
openapi.yaml
openapi/paths/cases/push/public@api@publicacao@por_pagina-get.yaml

[AB#23974](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/23974)

docs: setting 'status' property as optional

---

dist/cases.json
openapi.yaml
openapi/paths/cases/push/public@api@publicacao@por_pagina-get.yaml

updating status property as optional
ordering properties by required | optional
[AB#23974](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/23974)

docs: fixing properties

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/paths/cases/funcionario/public@api@funcionarios@categoriaseareas-get.yaml

[AB#23997](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/23997)

Atualização de documentação de endpoints para Web

---

dist/cases.json
openapi.yaml
openapi/paths/cases/funcionario/public@api@funcionarios@categoriaseareas-get.yaml

[AB#23997](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/23997)

fix(openapi): Adicionando prop AreaPadrao no Funcionario

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOPrazoPublicacao.yaml

[AB#24325](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/24325)

Add prop IDCaso no DTOPrazoPublicacao

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTOTarefa.yaml
openapi/components/schemas/cases/DTOTarefaResponse.yaml
openapi/components/schemas/cases/enums/SituacaoDoItemAgenda.yaml
openapi/components/schemas/cases/enums/SituacaoLembrete.yaml
openapi/components/schemas/cases/enums/TipoTarefa.yaml
openapi/paths/cases/push/public@api@publicacao@tarefas-post.yaml
openapi/paths/cases/tarefa/public@api@tarefas-post.yaml

docs: add api/publicacao/tarefas doc

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/enums/SituacaoLembrete.yaml

docs: removing none from enum

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOTarefa.yaml
openapi/components/schemas/cases/DTOTarefaResponse.yaml
openapi/components/schemas/cases/enums/SituacaoDoItemAgenda.yaml
openapi/components/schemas/cases/enums/TipoTarefa.yaml

docs: fix DTOTarefa response

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOTarefaResponse.yaml

docs: add property CustomFields to task response object

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOTarefa.yaml

docs: updating docs

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTOTarefaResponse.yaml
openapi/paths/cases/tarefa/public@api@tarefas@tarefas_subtarefas-get.yaml

[AB#24646](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/24646)

feat(Tarefas): Documentação do novo endpoint de tarefas e subtarefas

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/paths/cases/tarefa/public@api@agenda@titulos-post.yaml
openapi/paths/cases/tarefa/public@api@agenda@titulos-put.yaml

[AB#24700](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/24700)

docs: docs create / edit task titles

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOTituloAgenda.yaml
openapi/components/schemas/cases/DTOTituloAgendaResponse.yaml
openapi/components/schemas/cases/enums/TipoEventoDeCobranca.yaml
openapi/components/schemas/cases/enums/TipoItemAgenda.yaml
openapi/paths/cases/tarefa/public@api@agenda@titulos-get.yaml
openapi/paths/cases/tarefa/public@api@agenda@titulos-post.yaml

[AB#24700](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/24700)

docs: updating task title documentation

---

.redocly.yaml
dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOCustomFields.yaml
openapi/components/schemas/cases/DTOItemAgenda.yaml
openapi/paths/cases/tarefa/public@api@agenda@custom_field-post.yaml

[AB#24887](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/24887)

docs: custom_fields documentation

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOCustomFields.yaml

[AB#24887](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/24887)

docs: fixing description

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOTituloAgendaResponse.yaml

[AB#25089](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25089)

fix: adding property 'TipoTarefa' to DTOTituloAgendaResponse

---

dist/cases.json
openapi.yaml
openapi/paths/cases/tarefa/public@api@agenda@titulos-put.yaml

[AB#25249](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25249)

fix: changing response object

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTOTituloAgenda.yaml
openapi/components/schemas/cases/DTOTituloAgendaResponse.yaml
openapi/paths/cases/tarefa/public@api@tarefas@titulos-get.yaml

[AB#24738](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/24738)

feat: api/tarefas/titulos doc

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOTarefaResponse.yaml

[AB#25368](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25368)

fix: adding properties to DTOTarefaResponse.yaml

---

dist/cases.json
openapi.yaml
openapi/paths/cases/tarefa/public@api@tarefas@tarefas_subtarefas-get.yaml

[AB#25368](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25368)

fix: updating docs

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/DTOMotivoDePedir.yaml
openapi/paths/cases/motivos/public@api@propositionStatement-post.yaml
openapi/paths/cases/motivos/public@api@propositionStatements-get.yaml
openapi/paths/cases/motivos/public@api@propositionStatements@id-get.yaml

[AB#25384](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25384)

docs: propositionStatements endpoints docs

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOMotivoDePedir.yaml

[AB#25384](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25384)

docs: updating property description

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/DTOCasoPedidoSimples.yaml
openapi/components/schemas/cases/enums/ExpectativaReivindicacao.yaml
openapi/components/schemas/cases/enums/TipoReparacao.yaml
openapi/components/schemas/cases/enums/eSituacaoDePedido.yaml

[AB#25410](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25410)

docs: updating examples in DTOCasoPedidoSimples.yaml

---

dist/cases.json
openapi.yaml
openapi/cases.yaml
openapi/components/schemas/cases/Address.yaml
openapi/components/schemas/cases/Party.yaml
openapi/paths/cases/partes/public@api@partes@idParte-patch.yaml

[AB#25461](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25461)

docs: api/parte [PATCH] doc

---

dist/cases.json
openapi.yaml
openapi/components/schemas/cases/enums/TipoDeRecorrencia.yaml

[AB#25440](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25440)

feat: adding 0: Sem recorrência in enum TipoDeRecorrencia

---

api_yaml_files/cases.yaml
api_yaml_files/paths/cases/tarefa/public@api@tarefa@tarefa_subtarefas@id@tipo-get.yaml
app/v1/cases/cases.json

[AB#25537](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25537)

docs: docs from api/tarefas/tarefa_subtarefas/{id}/{tipo}

---

api_yaml_files/components/schemas/cases/DTOCasoPedidoSimples.yaml
app/v1/cases/cases.json

MotivoDePedir, ValorPrevistoAtualizado and ValorContingenciaAtualizado
[AB#25526](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25526)

fix: add properties to DTOCasoPedidoSimples

---

README.md
api_config_files/build_apis.json
api_yaml_files/components/schemas/cases/ProcessosCadastradosResposta.yaml
app/v1/cases/cases.json
help/build_new_api.md
help/help.json
package.json

[AB#25965](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/25965)

fix: adding two properties

---

api_yaml_files/cases.yaml
api_yaml_files/components/schemas/cases/DTOCasoCompleto.yaml
api_yaml_files/components/schemas/cases/DTOCustomFields.yaml
api_yaml_files/paths/cases/casos/public@api@casos@edit-put.yaml
api_yaml_files/paths/cases/casos/public@api@casos@edit@custom_fields-post.yaml
api_yaml_files/paths/cases/casos/public@api@casos@editadosrecentemente-get.yaml
api_yaml_files/paths/cases/casos/public@api@casos@inclui-post.yaml
api_yaml_files/paths/cases/casos/public@api@casos@por_pagina-get.yaml
api_yaml_files/paths/cases/informacoes_adicionais/public@api@dado_complementar-post.yaml
api_yaml_files/paths/cases/motivos/public@api@propositionStatement-post.yaml
api_yaml_files/paths/cases/tarefa/public@api@agenda@custom_field-post.yaml
api_yaml_files/paths/cases/tarefa/public@api@agenda@edit-put.yaml
api_yaml_files/paths/cases/tarefa/public@api@agenda@titulos-post.yaml
api_yaml_files/paths/cases/tarefa/public@api@tarefas-post.yaml
api_yaml_files/paths/varas_foros/public@v2@court-post.yaml
api_yaml_files/paths/varas_foros/public@v2@sequence-post.yaml
app/v1/cases/cases.json
app/v1/cases/page.js

docs: add properties to DTOs

---

api_yaml_files/components/schemas/cases/DTOMultaSucumbencia.yaml
api_yaml_files/components/schemas/cases/DTOProcessoDecisao.yaml
api_yaml_files/components/schemas/cases/enums/MultaSucumbencia.yaml
api_yaml_files/components/schemas/cases/enums/SituacaoJulgamento.yaml
api_yaml_files/components/schemas/cases/enums/ValorApuradoExitoPerda.yaml
api_yaml_files/components/schemas/cases/enums/eSituacaoDePedido.yaml
app/v1/cases/cases.json
package.json

[AB#28810](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/28810)
[AB#28802](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/28802)
[AB#28788](https://dev.azure.com/looplex/b82e5d65-1e2b-4483-8c8d-72a12b569c9d/_workitems/edit/28788)

feat: doc MultaSucumbencia
